### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by cmb69** [TN03/jQuery_XH#2]
I'm planning to [release CMSimple_XH 1.7.3 soonish](https://cmsimpleforum.com/viewtopic.php?f=29&t=14223) (ideally second half of November), so it would be great to have an up-to-date jQuery4CMSimple.

Latest version is presently [jQuery 3.3.1](https://github.com/jquery/jquery/releases/tag/3.3.1). The migrate plugins (1.4.1 and 3.0.0) are already up-to-date, as is jQueryUI (1.12.1).

Given that support for jQuery 1 and 2 has been ceased (apparently, long ago, since the latest commits to the [1.12-stable](https://github.com/jquery/jquery/tree/1.12-stable) and [2.2-stable](https://github.com/jquery/jquery/tree/2.2-stable) branches had been on 2016-06-09), we may consider to remove the old versions.

We also should consider the future of jQueryUI in jQuery4CMSimple. It seems to me that jQueryUI is practically abandoned (latest commit has been on 2017-05-31; latest release on 2016-09-14), so perhaps it's time to deprecate jQueryUI (cf. #1)?

**Comment by TN03** [comment]
Fixed with https://github.com/TN03/jQuery_XH/commit/e81611eb7a107dd8ebeda194e2611f80751774ad
